### ISSUE TITLE
Wrong relative links from the "What's new" pages.

### ISSUE THREAD

**Issue by flatombe** [eclipse-sirius/sirius-website#4]
* 1: Go to any "What's new" page, e.g. https://eclipse.dev/sirius/whatsnew/whatsnew5.html
* 2: Links in the top menu, e.g. "Gallery" point to https://eclipse.dev/sirius/whatsnew/gallery.html
* 3: KO => the correct link is https://eclipse.dev/sirius/gallery.html

**Comment by pcdavid** [comment]
Fixed by https://github.com/eclipse-sirius/sirius-website-sources/commit/cdbffe670a377268dac5aa8895e9bbc47a20029d.
